

const screenId = {
    ChooseDeposite:"B21.ChooseDeposite",
    SellCoins:"B21.SellScreen",
    LoginScreen: "B21.LoginScreen",
    SignUpScreen: "B21.SignUpScreen",
    SetPasswordScreen: "B21.SetPasswordScreen",
    AddMobileNumberScreen: "B21.AddMobileNumberScreen",
    VerifyMobileNumberScreen: "B21.VerifyMobileNumberScreen",
    TermsAndConditionsScreen: "B21.TermsAndConditionsScreen",
    WelcomeOneScreen: "B21.WelcomeOneScreen",
    WelcomeSecondScreen: "B21.WelcomeSecondScreen",
    WelcomeScreen: "B21.WelcomeScreen",
    CountryNotSupportedScreen: "B21.CountryNotSupportedScreen",
    CreateGoalScreen: "B21.CreateGoalScreen",
    LearnScreen: "B21.LearnScreen",
    MenuScreen: "B21.MenuScreen",
    SetGoalAmountScreen: "B21.SetGoalAmountScreen",
    ChooseGoalCurrencyScreen: "B21.ChooseGoalCurrencyScreen",
    ChooseGoalCryptoCurrencyScreen: "B21.ChooseGoalCryptoCurrencyScreen",
    SetGoalDateScreen: "B21.SetGoalDateScreen",
    GoalSummaryScreen: "B21.GoalSummaryScreen",
    ConfirmYourCountryScreen: "B21.ConfirmYourCountryScreen",
    ChooseGoalCryptoCurrencyCustomizeScreen: "B21.ChooseGoalCryptoCurrencyCustomizeScreen",
    GoalInvestConfirmScreen: "B21.GoalInvestConfirmScreen",
    KYCAddressScreen:"B21.KYCAddressScreen",
    KYCConfirmNameScreen: "B21.KYCConfirmNameScreen",
    KYCDateOfBirthScreen: "B21.KYCDateOfBirthScreen",
    KYCAdditionalInformationScreen: "B21.KYCAdditionalInformationScreen",
    KYCUniqueIdentificationScreen: "B21.KYCUniqueIdentificationScreen",
    KYCConfirmEmailScreen: "B21.KYCConfirmEmailScreen",
    KYCSourceOfFundsScreen: "B21.KYCSourceOfFundsScreen",
    KYCDocumentUploadScreen: "B21.KYCDocumentUploadScreen",
    GoalDashboardScreen: "B21.GoalDashboardScreen",
    KYCCongratulationsScreen: "B21.KYCCongratulationsScreen",
    ChooseInvestmentMethodScreen: "B21.ChooseInvestmentMethodScreen",
    DebitCardSelectPaymentInstrumentScreen: "B21.DebitCardSelectPaymentInstrumentScreen",
    InvestmentAmountScreen: "B21.InvestmentAmountScreen",
    InvestmentSummaryScreen: "B21.InvestmentSummaryScreen",
    DebitCardAdditionalInformationScreen: "B21.DebitCardAdditionalInformationScreen",
    InvestmentCashBalanceAmountScreen: "B21.InvestmentCashBalanceAmountScreen",
    InvestmentTransactionSummaryScreen: "B21.InvestmentTransactionSummaryScreen",
    InvestmentCashBalanceSummaryScreen: "B21.InvestmentCashBalanceSummaryScreen",
    InvestmentCashBalanceTansactionSummaryScreen: "B21.InvestmentCashBalanceTansactionSummaryScreen",
}

export default screenId;